#!/bin/bash

echo Deleting old build directory
rm -rf build
rm -rf CMakeCache.txt CMakeFiles
echo Creating new build directory
mkdir build
cd build
echo Configuring....
cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/bin/ -DBUILD_TESTING=OFF
echo ""
echo ""
read -p "Finished. Press any key to open ccmake and double ceck all settings. Remember to set CMAKE_INSTALLATION_PREFIX to the install directory " -n1 -s
ccmake ../
echo ""
echo ""
echo "********** IMPORTANT ************"
echo Done, now change into the build directory, then type make and make install
echo "**********************************"
