#!/bin/bash

echo Deleting old build directory
rm -rf build
rm -rf CMakeCache.txt CMakeFiles
echo Creating new build directory
mkdir build
cd build
echo Configuring....
export HDF5_ROOT=/reg/g/cfel/dependencies/
export PATH=~filipe/cmake/bin:${PATH}
source /reg/g/psdm/etc/psconda.sh
#source /reg/g/psdm/etc/ana_env.sh

cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/reg/g/cfel/cheetah/cheetah-stable/ -DBUILD_PSANA=ON -DBUILD_CHEETAH_PSANA=ON -DPYTHON_LIBRARY=/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.3.47/lib/libpython2.7.so -DPYTHON_INCLUDE_DIR=/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.3.47/include/python2.7 -DANA_RELEASE=/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.3.47 -DANA_SIT_DATA=/reg/g/psdm/data
#cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/reg/g/cfel/cheetah/cheetah-stable/ -DBUILD_PSANA=ON -DBUILD_CHEETAH_ANA_MOD=ON -DPYTHON_LIBRARY=/reg/g/psdm/sw/releases/ana-current/arch/x86_64-rhel7-gcc48-opt/lib/libpython2.7.so -DPYTHON_INCLUDE_DIR=/reg/g/psdm/sw/releases/ana-current/arch/x86_64-rhel7-gcc48-opt/geninc/python/

echo ""
echo ""
read -p "Finished. Press any key to open ccmake and double ceck all settings. Remember to set CMAKE_INSTALLATION_PREFIX to the install directory " -n1 -s
ccmake ../
echo ""
echo ""
echo "********** IMPORTANT ************"
echo Done, now change into the build directory, then type make and make install
echo "**********************************"
